### ISSUE TITLE
Add python packages: paho-mqt and requests

### ISSUE THREAD

**Issue by epajfl00** [chrisp250/daikin_mqtt#1]
Hi,
    Great to see that someone has finally made an attempt to get Daikin AC working again on HA.

For a novice, how exactly do you add the required python packages to HA? 
I've never had to do this before, usually done automatically via scripts etc....

Do you create a script file (named anything??, or special name and extension?) with the following contents in folder Addon-configs:
{
  "log_level": "info",
  "system_packages": [  ],
  "python_packages": [
    "paho-mqtt",
    "requests"
  ]
}

Do you then restart HA or reboot?, and the packages will be install automatically then delete that file fro addon-config.

**Comment by chrisp250** [comment]
I don't run this code in Home Assistant. I use a separate machine, in my case a virtual machine running on a Proxmox server.
I'm not sure how it would behave running on Home Assistant, but you could try with pip see if it would install the packages:
`pip install paho-mqtt`

Also please note after I published the code, I realised that the file called `daikin` should be called `daikin.py`
Cheers

**Comment by chrisp250** [comment]
I was provided an update to generate a docker package. That might help people that don't have a dedicated server.

I'm closing this issue.
