### ISSUE TITLE
Release won't run

### ISSUE THREAD

**Issue by chrisp250** [chrisp250/daikin_mqtt#13]
Hi @foxdalas,
I tried to run the release workflow but it's giving me errors.
Initially it couldn't find the release-drafter file, I moved it to the `.github` folder and renamed the extension from yaml to yml and now it picks it up, however it still complains there's a problem with it:

```
chrisp250/daikin_mqtt: Config validation errors, please fix the following issues in release-drafter.yml:
┌──────────┬────────────────────────┐
│ Property │ Error                  │
├──────────┼────────────────────────┤
│ template │ "template" is required │
└──────────┴────────────────────────┘
```

Would you mind giving us a hand?
Thank you

**Comment by foxdalas** [comment]
@chrisp250 I'm going to fix it
